// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated from a template.
// 
//      Manual changes to this fichier may cause unexpected behavior in your application.
//      Manual changes to this fichier will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace BorderSource.BetsyContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class article
    {
        public article()
        {
            this.biggest_price_differences = new HashSet<biggest_price_differences>();
            this.country_price_differences = new HashSet<country_price_differences>();
            this.ean = new HashSet<ean>();
            this.product = new HashSet<product>();
            this.sku = new HashSet<sku>();
            this.title = new HashSet<title>();
            this.vbob_suggested = new HashSet<vbob_suggested>();
            this.category = new HashSet<category>();
        }
    
        public int id { get; set; }
        public string brand { get; set; }
        public string description { get; set; }
        public string image_loc { get; set; }
    
        public virtual ICollection<biggest_price_differences> biggest_price_differences { get; set; }
        public virtual ICollection<country_price_differences> country_price_differences { get; set; }
        public virtual ICollection<ean> ean { get; set; }
        public virtual ICollection<product> product { get; set; }
        public virtual ICollection<sku> sku { get; set; }
        public virtual ICollection<title> title { get; set; }
        public virtual ICollection<vbob_suggested> vbob_suggested { get; set; }
        public virtual ICollection<category> category { get; set; }
    }
}
