// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated from a template.
// 
//      Manual changes to this file may cause unexpected behavior in your application.
//      Manual changes to this file will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace BorderSource.BetsyContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class categorytemp
    {
        public categorytemp()
        {
            this.articletemp = new HashSet<articletemp>();
        }
    
        public int id { get; set; }
        public string description { get; set; }
        public Nullable<int> called_by { get; set; }
    
        public virtual ICollection<articletemp> articletemp { get; set; }
    }
}
