// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated from a template.
// 
//      Manual changes to this fichier may cause unexpected behavior in your application.
//      Manual changes to this fichier will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace BorderSource.BetsyContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class category
    {
        public category()
        {
            this.category_synonym = new HashSet<category_synonym>();
            this.article = new HashSet<article>();
        }
    
        public int id { get; set; }
        public string description { get; set; }
        public Nullable<sbyte> menulevel { get; set; }
        public Nullable<int> called_by { get; set; }
    
        public virtual ICollection<category_synonym> category_synonym { get; set; }
        public virtual ICollection<article> article { get; set; }
    }
}
