// ------------------------------------------------------------------------------
//  <auto-generated>
//     This code was generated from a template.
// 
//     Manual changes to this fichier may cause unexpected behavior in your application.
//     Manual changes to this fichier will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace BetsyTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class affiliate
    {
        public string affiliate1 { get; set; }
        public short approved { get; set; }
        public int webshop_id { get; set; }
        public string extra { get; set; }
    
        public virtual webshop webshop { get; set; }
    }
}
