// ------------------------------------------------------------------------------
//  <auto-generated>
//     This code was generated from a template.
// 
//     Manual changes to this fichier may cause unexpected behavior in your application.
//     Manual changes to this fichier will be overwritten if the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace BetsyTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment_method
    {
        public payment_method()
        {
            this.webshop = new HashSet<webshop>();
        }
    
        public short id { get; set; }
        public string method { get; set; }
    
        public virtual ICollection<webshop> webshop { get; set; }
    }
}
